"""Rich DOCX fixture factory; generated at test time to keep binary blobs out of git."""

from __future__ import annotations

import io
import zipfile
from pathlib import Path

from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_BREAK
from docx.oxml import parse_xml
from docx.shared import Cm, Pt
from PIL import Image, ImageDraw


def build_complex_docx(path: Path) -> None:
    document = Document()
    section = document.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = Cm(29.7), Cm(21)
    section.top_margin = Cm(1.8)
    section.bottom_margin = Cm(1.8)
    document.styles["Normal"].font.name = "Arial"
    document.styles["Normal"].font.size = Pt(11)
    document.add_heading("Rich document", level=1)
    paragraph = document.add_paragraph("Styled text ")
    run = paragraph.add_run("bold italic")
    run.bold = True
    run.italic = True
    document.add_paragraph("First page body").add_run().add_break(WD_BREAK.PAGE)
    document.add_heading("Second page", level=2)
    table = document.add_table(rows=2, cols=3)
    table.style = "Table Grid"
    for row_index, row in enumerate(table.rows):
        for column_index, cell in enumerate(row.cells):
            cell.text = f"R{row_index + 1}C{column_index + 1}"

    image = Image.new("RGB", (160, 80), "white")
    ImageDraw.Draw(image).rectangle((10, 10, 150, 70), fill="#ff8a00")
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    document.add_picture(buffer, width=Cm(5))

    header = section.header
    header.paragraphs[0].text = "Focus rich header"
    footer = section.footer
    footer.paragraphs[0].text = "Focus rich footer"
    watermark = parse_xml(
        "<w:r xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main' "
        "xmlns:v='urn:schemas-microsoft-com:vml' "
        "xmlns:o='urn:schemas-microsoft-com:office:office'>"
        "<w:pict><v:shape id='FocusWatermark' o:spid='_x0000_s1025' type='#_x0000_t136' "
        "style='position:absolute;width:420pt;height:80pt;rotation:315;z-index:-251654144' "
        "fillcolor='silver' stroked='f'><v:textpath style='font-family:Arial;font-size:1pt' "
        "string='Generated by AI'/></v:shape></w:pict></w:r>"
    )
    header.paragraphs[0]._p.append(watermark)
    document.save(path)
    with zipfile.ZipFile(path, "a") as package:
        package.writestr("customXml/focus-extension.bin", b"opaque-extension-must-survive")


def mutate_main_document(source: Path) -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(source) as original, zipfile.ZipFile(output, "w") as modified:
        for info in original.infolist():
            payload = original.read(info.filename)
            if info.filename == "word/document.xml":
                payload = payload.replace(b"First page body", b"Edited first page body", 1)
            modified.writestr(info, payload)
    return output.getvalue()
