/* 本文件对外提供隐藏 Electron 中两种真实页面的隔离验收。
 * 输入为新 userData 目录、生产 index.html 与离线 API fixture；输出为目录选择、四类输入、草稿、观测和中断过渡/检查身份断言。
 * 工作流为无可见窗口加载完整应用，操作默认折叠、六导航、按需检查与单路 Live，核对请求可见身份、关系图装备/键盘选择及边对账；普通会话继续展示原 Agent 消息。截图只证明布局，离线 fixture 不代替业务端到端。
 * 示例：node --test desktop/workspace-patrol-page.test.cjs。没有外部 Provider、生产库或安装应用写入。
 */
const assert = require("node:assert/strict");
const path = require("node:path");
const fs = require("node:fs");
const os = require("node:os");
if (!process.versions.electron) {
  require("node:test")("Patrol and ordinary pages in hidden Electron", () => {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), "focus-patrol-ui-"));
    const env = { ...process.env, FOCUS_PATROL_TEST_USER_DATA: directory };
    delete env.ELECTRON_RUN_AS_NODE;
    const result = require("node:child_process").spawnSync(require("electron"), [__filename], { env, encoding: "utf8", timeout: 90000, windowsHide: true });
    assert.equal(result.status, 0, result.stdout + result.stderr);
    assert.match(result.stdout, /PATROL_UI_PASS/);
  });
} else {
  const { app, BrowserWindow } = require("electron");
  app.setPath("userData", process.env.FOCUS_PATROL_TEST_USER_DATA);
  app.disableHardwareAcceleration();
  app.whenReady().then(async () => {
    const win = new BrowserWindow({ show: false, width: 1280, height: 900, webPreferences: { contextIsolation: false, sandbox: false, backgroundThrottling: false, offscreen: true, preload: path.join(__dirname, "workspace-patrol-test-preload.cjs") } });
    const errors = [];
    win.webContents.on("console-message", (_event, _level, message) => { if (message?.includes("Uncaught")) errors.push(message); });
    await win.loadFile(path.join(__dirname, "index.html"));
    const run = async expression => {
      try { return await win.webContents.executeJavaScript(expression, true); }
      catch (error) { throw new Error(`Page expression failed: ${expression}`, { cause: error }); }
    };
    const until = async expression => {
      const end = Date.now() + 8000;
      while (!await run(`Boolean(${expression})`)) { if (Date.now() > end) throw new Error(`Timeout: ${expression} · ${await run('JSON.stringify({view:state.view,task:state.activeTaskId,draftOpens:window.patrolFixture.draftOpens,status:document.querySelector("#globalStatus")?.textContent,focused:document.activeElement?.outerHTML?.slice(0,250)})')}`); await new Promise(resolve => setTimeout(resolve, 20)); }
    };
    await until('document.body.dataset.view === "patrol" && document.querySelector("[data-patrol-content]")');
    assert.equal(await run('document.querySelectorAll("[data-nav-key]").length'), 6);
    assert.equal(await run('document.querySelector("[data-patrol-content]").disabled'), true);
    assert.equal(await run('Boolean(document.querySelector("[data-patrol-details-content]"))'), false);
    if (process.env.FOCUS_FRONTEND_QA_DIR) await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    if (process.env.FOCUS_FRONTEND_QA_DIR) fs.writeFileSync(path.join(process.env.FOCUS_FRONTEND_QA_DIR, "current-" + (await run("document.body.dataset.view")) + ".png"), (await win.webContents.capturePage()).toPNG());
    await run('document.querySelector("[data-action=focus-home]").click()');
    await until('document.body.dataset.view === "focus" && document.querySelector(".conversation-message, .message")');
    const ordinary = await run('document.querySelector("#app").textContent');
    assert.ok(ordinary.length > 100);
    await run('localStorage.setItem("focus-patrol-workspace", "old-database-workspace-id"); document.querySelector("[data-action=show-patrol][data-patrol-switch]").click()');
    await until('document.querySelector("[data-patrol-bind]")');
    assert.equal(await run('Boolean(document.querySelector("[data-patrol-search], [data-patrol-workspaces], [data-patrol-enter]"))'), false);
    await run('document.querySelector("[data-patrol-bind]").click()');
    await until('!document.querySelector("[data-patrol-bind]").disabled');
    assert.equal(await run('window.patrolFixture.workspaceBinds.length'), 0);
    await run('window.patrolFixture.folderError=true; document.querySelector("[data-patrol-bind]").click()');
    await until('!document.querySelector("[data-patrol-binding-error]").hidden');
    assert.ok((await run('document.querySelector("[data-patrol-binding-error]").textContent')).includes("文件夹选择失败"));
    const chosen = "C:/picked/from-filesystem/很长的项目父目录/project";
    await run(`window.patrolFixture.folderError=false; window.patrolFixture.folder=${JSON.stringify(chosen)}; document.querySelector("[data-patrol-bind]").click()`);
    await until('document.querySelector("[data-patrol-enter]")');
    assert.equal(await run('document.querySelector(".patrol-workspace-path").textContent'), chosen);
    assert.equal(await run('window.patrolFixture.workspaceBinds.length'), 0);
    assert.equal(await run('document.activeElement.hasAttribute("data-patrol-enter")'), true);
    await run('render()');
    assert.equal(await run('document.querySelector(".patrol-workspace-path").textContent'), chosen);
    await run('window.patrolFixture.folder=null; document.querySelector("[data-patrol-bind]").click()');
    await until('!document.querySelector("[data-patrol-bind]").disabled');
    assert.equal(await run('document.querySelector(".patrol-workspace-path").textContent'), chosen);
    win.setContentSize(720, 800);
    assert.equal(await run('document.documentElement.scrollWidth > innerWidth'), false);
    win.setContentSize(1280, 900);
    await run('window.patrolFixture.bindError=true; document.querySelector("[data-patrol-enter]").click()');
    await until('!document.querySelector("[data-patrol-binding-error]").hidden');
    assert.ok((await run('document.querySelector("[data-patrol-binding-error]").textContent')).includes("工作区绑定失败"));
    await run('window.patrolFixture.bindError=false; document.querySelector("[data-patrol-enter]").click()');
    await until('document.querySelector("[data-patrol-content]")');
    assert.equal(await run('window.patrolFixture.workspaceBinds.at(-1).path'), chosen);
    assert.equal(await run('window.patrolFixture.submissions.length'), 0);
    const calls = await run('window.patrolFixture.folderCalls');
    await run('document.querySelector("[data-action=show-patrol][data-patrol-switch]").click()');
    await until('document.querySelector("[data-patrol-bind]")');
    await run('window.patrolFixture.folder="C:/late/selected"; window.patrolFixture.holdFolder=true; document.querySelector("[data-patrol-bind]").click(); document.querySelector("[data-patrol-bind]").click()');
    await until('Boolean(window.patrolFixture.releaseFolder)');
    assert.equal(await run('window.patrolFixture.folderCalls'), calls + 1);
    await run('document.querySelector("[data-action=focus-home]").click(); window.patrolFixture.releaseFolder(); window.patrolFixture.holdFolder=false');
    await until('document.body.dataset.view === "focus"');
    assert.equal(await run('Boolean(document.querySelector(".patrol-workspace-picker"))'), false);
    await run('document.querySelector("[data-action=show-patrol][data-patrol-switch]").click()');
    await until('document.querySelector("[data-patrol-switch]")');
    await run('document.querySelector("[data-patrol-switch]").click()');
    await until('document.querySelector("[data-patrol-bind]")');
    await run('window.patrolFixture.folder="C:/late/binding"; document.querySelector("[data-patrol-bind]").click()');
    await until('document.querySelector("[data-patrol-enter]")');
    await run('window.patrolFixture.holdBind=true; document.querySelector("[data-patrol-enter]").click()');
    await until('Boolean(window.patrolFixture.releaseBind)');
    await run('document.querySelector("[data-action=focus-home]").click(); window.patrolFixture.releaseBind(); window.patrolFixture.holdBind=false');
    await until('document.body.dataset.view === "focus"');
    assert.equal(await run('JSON.parse(localStorage.getItem("focus-patrol-workspace")).path'), chosen);
    await run('localStorage.removeItem("focus-patrol-workspace")');
    for (const input_type of ["information", "outcome", "boundary", "completion_check"]) {
      await run('document.querySelector("[data-action=show-patrol][data-patrol-switch]").click()');
      await until('document.querySelector("[data-patrol-bind]")');
      await run(`window.patrolFixture.folder=${JSON.stringify("C:/test/" + input_type)}; document.querySelector("[data-patrol-bind]").click()`);
      await until('document.querySelector("[data-patrol-enter]")');
      await run('document.querySelector("[data-patrol-enter]").click()');
      await until('document.querySelector("[data-patrol-content]")');
      await run(`document.querySelector("[data-patrol-type]").value = ${JSON.stringify(input_type)}; document.querySelector("[data-patrol-type]").dispatchEvent(new Event("change")); document.querySelector("[data-patrol-content]").value="首条模糊信息"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit()`);
    await until('document.querySelector("[data-patrol-history]").textContent.includes("已受理")');
      const body = await run('window.patrolFixture.submissions.at(-1)');
      assert.equal(body.input_type, input_type);
      assert.ok(!body.context_id && !body.mode);
      assert.equal(await run('document.querySelector("[data-patrol-details-content]").hidden'), true);
    }
    await run('window.savedPatrolComposer = document.querySelector("[data-patrol-composer]"); render()');
    assert.equal(await run('window.savedPatrolComposer === document.querySelector("[data-patrol-composer]")'), true);
    const beforeIME = await run('window.patrolFixture.submissions.length');
    await run('document.querySelector("[data-patrol-content]").dispatchEvent(new KeyboardEvent("keydown", {key:"Enter",isComposing:true,bubbles:true,cancelable:true}))');
    assert.equal(await run('window.patrolFixture.submissions.length'), beforeIME);
    await run('window.patrolFixture.failReply=true; document.querySelector("[data-patrol-content]").value="丢失回执后重试"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit()');
    await until('document.querySelector("[data-patrol-retry]")');
    const failedIdentity = await run('window.patrolFixture.submissions.at(-1).submission_id');
    await run('document.querySelector("[data-patrol-history-open]").click(); document.querySelector("[data-patrol-retry]").click()');
    await until('!document.querySelector("[data-patrol-retry]")');
    assert.equal(await run('window.patrolFixture.submissions.at(-1).submission_id'), failedIdentity);
    await run('document.querySelector("[data-patrol-dialog-close]").click()');
    await run('window.patrolFixture.hold = true; document.querySelector("[data-patrol-content]").value="A"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit(); document.querySelector("[data-patrol-content]").value="B"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit(); document.querySelector("[data-patrol-content]").value="C 草稿"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input"))');
    await until('window.patrolFixture.releases.length === 2');
    await run('window.patrolFixture.releases[1](); window.patrolFixture.releases[0](); window.patrolFixture.hold=false');
    await until('Array.from(document.querySelectorAll("[data-patrol-history] article")).every(row => row.textContent.includes("已受理"))');
    assert.equal(await run('document.querySelector("[data-patrol-content]").value'), "C 草稿");
    await run('document.querySelector("[data-patrol-composer]").requestSubmit()');
    await until('window.patrolFixture.submissions.at(-1).content === "C 草稿"');
    assert.equal(await run('document.querySelectorAll("[data-patrol-history] article").length'), 3);
    await run('document.querySelector("[data-patrol-fold]").click()');
    assert.equal(await run('document.querySelectorAll("[data-patrol-history] article").length'), 5);
    await run('window.patrolFixture.emit("loop-completion_check", "loop_wait_request", "question", 1, { status:"open", scope:{information_only:true}, prompt:"使用密码还是验证码？" })');
    await until('document.querySelector("[data-patrol-answer]")');
    await run('document.querySelector("[data-patrol-pending]").click(); document.querySelector("[data-patrol-answer]").click()');
    assert.match(await run('document.querySelector("[data-patrol-target]").textContent'), /question · 版本 1/);
    await run('document.querySelector("[data-patrol-content]").value="用验证码"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit()');
    await until('window.patrolFixture.submissions.at(-1).request_id === "question"');
    assert.equal(await run('Boolean(document.querySelector("[data-patrol-answer]"))'), true);
    await run('window.patrolFixture.emit("loop-completion_check", "loop_wait_request", "question-next", 3, {status:"open",scope:{information_only:true},prompt:"下一项决定"})');
    await until('document.querySelector("[data-patrol-answer=question-next]")');
    await run('window.patrolFixture.releases=[]; window.patrolFixture.hold=true; document.querySelector("[data-patrol-pending]").click(); document.querySelector("[data-patrol-answer=question]").click(); document.querySelector("[data-patrol-content]").value="旧请求回答"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-composer]").requestSubmit()');
    await until('window.patrolFixture.releases.length === 1');
    await run('document.querySelector("[data-patrol-pending]").click(); document.querySelector("[data-patrol-answer=question-next]").click(); document.querySelector("[data-patrol-content]").value="新回答草稿"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); window.patrolFixture.hold=false; window.patrolFixture.releases.shift()()');
    await until('document.querySelector("[data-patrol-receipt]").textContent.includes("已受理")');
    assert.match(await run('document.querySelector("[data-patrol-target]").textContent'), /question-next · 版本 3/);
    assert.equal(await run('document.querySelector("[data-patrol-content]").value'), "新回答草稿");
    await run('document.querySelector("[data-patrol-clear-target]").click()');
    await run(`(async () => {
      const form=document.querySelector('[data-patrol-composer]'), input=document.querySelector('[data-patrol-content]');
      const details=document.querySelector('[data-patrol-details-content]');
      input.setSelectionRange(1,4); const draft=input.value;
      for (const interval of [40,80,120]) for(let i=0;i<7;i++) {
        form.querySelector('[data-patrol-details]').click();
        await new Promise(resolve=>setTimeout(resolve,interval));
        form.querySelector('[data-patrol-details]').click();
        if (!details.inert) throw new Error('退出详情仍可命中/Tab');
        await Promise.all([...form.getAnimations(),...details.getAnimations()].map(animation=>animation.finished.catch(()=>{})));
        if (!details.hidden || document.getAnimations().some(a=>a.effect.target===form)) throw new Error('反向过渡没有收口');
      }
      if (form!==document.querySelector('[data-patrol-composer]') || input.value!==draft || input.selectionStart!==1 || input.selectionEnd!==4) throw new Error('反向操作丢失输入');
      const panel=document.createElement('aside');panel.hidden=true;panel.className='patrol-context-drawer';panel.innerHTML='<div data-patrol-context-content></div>';document.body.append(panel);
      const replies=[];const inspector=FocusContextInspector.create({api:{conversation:()=>new Promise(resolve=>replies.push(resolve))},onOpenTask:()=>{throw new Error('检查不能打开任务')}});
      inspector.mount(panel);
      const first=inspector.select('loop-a','a',{title:'对象 A'},input);
      const second=inspector.select('loop-a','b',{title:'对象 B'},input);
      replies[1]({revision:{revision_id:'b-r'},messages:[]});await second;
      replies[0]({revision:{revision_id:'a-r'},messages:[]});await first;
      if (!panel.textContent.includes('b-r') || panel.textContent.includes('a-r')) throw new Error('迟到响应污染检查身份');
      inspector.close(); if (!panel.inert || document.activeElement!==input) throw new Error('关闭没有隔离命中/归还焦点');
      const reopen=inspector.select('loop-a','c',{title:'对象 C'},input); replies[2]({revision:{revision_id:'c-r'},messages:[]});await reopen;
      await new Promise(resolve=>setTimeout(resolve,240));
      if(panel.hidden || panel.inert || !panel.textContent.includes('c-r')) throw new Error('旧退出覆盖重开');
      inspector.close();await new Promise(resolve=>setTimeout(resolve,240));
      if(!panel.hidden || panel.getAnimations().length) throw new Error('抽屉退出未收口');
      inspector.dispose();panel.remove();
    })()`);
    await run('document.querySelector("[data-patrol-composer] [data-patrol-details]").click()');
    await win.webContents.debugger.attach("1.3");
    await win.webContents.debugger.sendCommand("Emulation.setEmulatedMedia", { features: [{ name: "prefers-reduced-motion", value: "reduce" }] });
    await until('document.querySelector("[data-patrol-composer]").getAnimations().length===0 && document.querySelector("[data-patrol-details-content]").getAnimations().length===0');
    await run('document.querySelector("[data-patrol-composer] [data-patrol-details]").click()');
    assert.equal(await run('document.querySelector("[data-patrol-details-content]").hidden && document.querySelector("[data-patrol-details-content]").inert'), true);
    await win.webContents.debugger.sendCommand("Emulation.setEmulatedMedia", { features: [] });
    await win.webContents.debugger.detach();
    await run('document.querySelector("[data-patrol-composer] [data-patrol-details]").click()');
    await run('window.patrolFixture.lineage = { roots:{root:"r1"}, nodes:[{context_id:"root",revision_id:"r1",generation:1}],edges:[],complete:true }; window.patrolFixture.emit("loop-completion_check", "context", "root", 1, {current_revision_id:"r1",title:"首线程"})');
    await until('document.querySelector("[data-patrol-lineage] [data-context-id=root]")');
    await run(`(() => {
      const manifest={nodes:Array.from({length:10},(_,i)=>({context_id:'stable-'+i,title:'稳定节点 '+i,revision:{generation:1},status:'active'})),edges:[]};
      const host=document.createElement('div');host.style.cssText='position:fixed;inset:0;width:400px;height:300px';host.innerHTML=FocusPortfolioMapView.render(manifest,null,[]);document.body.append(host);FocusPortfolioMapView.bind(host);
      host.querySelector('[data-portfolio-zoom=in]').click();
      const node=host.querySelector('[data-context-id="stable-0"]');node.focus({preventScroll:true});
      const scroll=host.querySelector('.portfolio-map-scroll');scroll.scrollLeft=30;const position=scroll.scrollLeft;
      const observer=new MutationObserver(()=>{});observer.observe(host,{subtree:true,attributes:true,childList:true,characterData:true});
      FocusPortfolioMapView.reconcile(host,manifest,null,[]);
      if(observer.takeRecords().length) throw new Error('未变图谱仍改写活动 DOM');
      manifest.nodes[0].title='真实元数据更新';FocusPortfolioMapView.reconcile(host,manifest,null,[]);
      if(node!==host.querySelector('[data-context-id="stable-0"]') || document.activeElement!==node || scroll.scrollLeft!==position || host.querySelector('.portfolio-map').dataset.zoom!=='1.15') throw new Error('元数据更新丢失图节点/焦点/阅读/缩放');
      observer.disconnect();host.remove();
      const table=document.createElement('table');table.innerHTML='<tbody></tbody>';document.body.append(table);
      const tbody=table.firstElementChild, facts=Array.from({length:20},(_,i)=>({fact_id:'stable-fact-'+i,revision:1,kind:'test',status:'observed',title:'事实 '+i}));
      FocusLoopFactsView.reconcileRows(tbody,facts);const factButton=tbody.querySelector('button');factButton.focus({preventScroll:true});
      observer.observe(tbody,{subtree:true,attributes:true,childList:true,characterData:true});FocusLoopFactsView.reconcileRows(tbody,facts);
      if(observer.takeRecords().length || document.activeElement!==factButton) throw new Error('未变事实仍移动行或丢失焦点');
      facts[0]={...facts[0],revision:2,status:'verified'};FocusLoopFactsView.reconcileRows(tbody,facts);
      if(document.activeElement?.dataset.factId!=='stable-fact-0' || !tbody.firstElementChild.textContent.includes('已验证')) throw new Error('真实事实修订未更新或丢失焦点');
      observer.disconnect();table.remove();
    })()`);
    await run('window.savedGraphNode=document.querySelector("[data-patrol-lineage] [data-context-id=root]"); window.patrolFixture.emit("loop-completion_check","context","root",2,{current_revision_id:"r1",title:"首线程更新"})');
    await until('document.querySelector("[data-patrol-lineage] [data-context-id=root]").textContent.includes("首线程更新")');
    assert.equal(await run('savedGraphNode===document.querySelector("[data-patrol-lineage] [data-context-id=root]")'), true);
    await run('window.patrolFixture.holdControl=true; window.patrolFixture.controlError=true; document.querySelector("[data-patrol-control=pause]").click()');
    assert.equal(await run('document.querySelector("[data-patrol-control=pause]").getAttribute("aria-busy")'), "true");
    assert.match(await run('document.querySelector("[data-patrol-state]").textContent'), /推进中/);
    await run('window.patrolFixture.releaseControl(); window.patrolFixture.holdControl=false');
    await until('document.querySelector("[data-patrol-error]").textContent.includes("工作控制读取失败")');
    assert.equal(await run('document.querySelector("[data-patrol-control=pause]").hasAttribute("aria-busy")'), false);
    assert.match(await run('document.querySelector("[data-patrol-state]").textContent'), /推进中/);
    await run('window.patrolFixture.controlError=false');
    await run('window.patrolFixture.observationError=true; window.patrolFixture.emit("loop-completion_check", "round", "round-1", 1, {number:1,observation_id:"observation-1"})');
    await until('document.querySelector("[data-patrol-observation-retry]")');
    await run('window.patrolFixture.observationError=false; document.querySelector("[data-patrol-observation-retry]").click()');
    await until('!document.querySelector("[data-patrol-observation-open]").disabled');
    await run('document.querySelector("[data-patrol-observation-open]").click(); document.querySelector("[data-patrol-observation-section=sources]").click()');
    await until('document.querySelector("[data-patrol-dialog]").textContent.includes("frozen-source")');
    const coverageText = await run('document.querySelector("[data-patrol-dialog]").textContent');
    assert.match(coverageText, /冻结来源覆盖：不完整/);
    assert.match(coverageText, /前序历史覆盖：不完整/);
    assert.match(coverageText, /来源关系覆盖：完整/);
    assert.match(coverageText, /当前冻结清单已读取 1 \/ 1 项/);
    await run('window.patrolFixture.emit("loop-completion_check", "round", "round-2", 1, {number:2,observation_id:"observation-2"})');
    await until('document.querySelector("[data-patrol-observation]").textContent.includes("Round 2")');
    assert.equal(await run('document.querySelector("[data-patrol-dialog]").textContent.includes("observation-1")'), true);
    assert.equal(await run('document.querySelector("[data-patrol-dialog]").textContent.includes("observation-2")'), false);
    await run('document.querySelector("[data-patrol-dialog-close]").click()');
    await run('document.querySelector("[data-patrol-grant-open]").click()');
    await until('document.querySelector("#agentLoopBudgetForm")');
    await run('document.querySelector("#agentLoopBudgetForm [name=maxRounds]").value="12"; document.querySelector("#agentLoopBudgetForm").requestSubmit(document.querySelector("#agentLoopBudgetForm button"))');
    await until('window.patrolFixture.grantChanges.length === 1');
    assert.equal(await run('window.patrolFixture.grantChanges[0].loopId'), "loop-completion_check");
    assert.equal(await run('window.patrolFixture.grantChanges[0].body.budgets.max_rounds'), 12);
    await run('document.querySelector("[data-patrol-dialog-close]").click(); window.patrolFixture.emit("loop-completion_check", "loop_wait_request", "typed-question", 1, {status:"open",response_mode:"text",prompt:"补充目标",response_contract:{max_length:200},scope:{}})');
    await until('document.querySelector("[data-wait-request-id=typed-question] textarea")');
    await run('document.querySelector("[data-patrol-pending]").click(); window.savedWaitInput=document.querySelector("[data-wait-request-id=typed-question] textarea"); savedWaitInput.value="保留回答草稿"; savedWaitInput.dispatchEvent(new Event("input",{bubbles:true})); savedWaitInput.focus(); savedWaitInput.setSelectionRange(1,4); window.patrolFixture.emit("loop-completion_check","fact","draft-update",1,{kind:"run",status:"observed",title:"Live 草稿验收更新"})');
    await until('document.querySelector("[data-patrol-facts]").textContent.includes("Live 草稿验收更新")');
    assert.equal(await run('document.querySelector("[data-wait-request-id=typed-question] textarea").value'), "保留回答草稿");
    assert.equal(await run('savedWaitInput===document.querySelector("[data-wait-request-id=typed-question] textarea") && document.activeElement===savedWaitInput && savedWaitInput.selectionStart===1 && savedWaitInput.selectionEnd===4'), true);
    await run('document.querySelector("[data-wait-request-id=typed-question] form").requestSubmit()');
    await until('window.patrolFixture.waitAnswers.length === 1');
    assert.equal(await run('window.patrolFixture.waitAnswers[0].answer.text'), "保留回答草稿");
    await run('document.querySelector("[data-patrol-dialog-close]").click()');
    await run('document.querySelector("[data-patrol-content]").value="查看时保留草稿"; document.querySelector("[data-patrol-content]").dispatchEvent(new Event("input")); document.querySelector("[data-patrol-lineage] [data-context-id=root]").click()');
    await until('document.querySelector("[data-patrol-context-tab=conversation]")');
    await run('document.querySelector("[data-patrol-context-tab=conversation]").click()');
    await until('document.querySelector("[data-patrol-context-content]").textContent.includes("Context 执行结果")');
    assert.equal(await run('document.body.dataset.view'), "patrol");
    assert.equal(await run('document.querySelector("[data-patrol-content]").value'), "查看时保留草稿");
    await run('document.querySelector("[data-patrol-context-tab=sources]").click()');
    await until('document.querySelector("[data-patrol-inspect-revision=r1]")');
    await run('document.querySelector("[data-patrol-inspect-revision=r1]").click()');
    await until('document.querySelector("[data-patrol-context-content]").textContent.includes("source-r1")');
    assert.equal(await run('document.querySelector("[data-patrol-inspect-revision=r1]").getAttribute("aria-pressed")'), "true");
    await run('window.patrolFixture.emit("loop-completion_check", "task_progress", "loop-completion_check", 2, {generation:1, document:{items:[{description:"已确认本地保存",state:"in_progress",support:"asserted"}]}})');
    await until('document.querySelector("[data-patrol-progress]").textContent.includes("已确认本地保存")');
    assert.equal(await run('document.querySelector("[data-patrol-lineage]").textContent.includes("首线程")'), true);
    await run('window.patrolFixture.emit("loop-completion_check", "fact", "run-fact", 1, { kind:"run",title:"另一个 Context 已完成",summary:"真实 Run 事实",context_id:"other-context",status:"success" })');
    await until('document.querySelector("[data-patrol-facts]").textContent.includes("另一个 Context 已完成")');
    const composer = await run('(() => { const r = document.querySelector("[data-patrol-content]").getBoundingClientRect(); return {top:r.top,bottom:r.bottom,height:innerHeight}; })()');
    assert.ok(composer.top >= 0 && composer.bottom <= composer.height, JSON.stringify(composer));
    assert.equal(await run('Boolean(document.querySelector("[data-patrol-answer]"))'), true);
    await run('document.querySelector("[data-patrol-open-task]").click()');
    await until('document.body.dataset.view === "focus" && state.activeTaskId === "root"');
    await run('document.querySelector("[data-nav-key=patrol]").click()');
    await until('document.querySelector("[data-patrol-content]")');
    assert.equal(await run('document.querySelector("[data-patrol-content]").value'), "查看时保留草稿");
    await win.webContents.reload();
    await until('document.body.dataset.view === "patrol" && document.querySelectorAll("[data-patrol-history] article").length === 3');
    assert.equal(await run('document.querySelector("#appInspector").hidden'), true);
    assert.equal(await run('document.querySelector(".shell-resizer-inspector").getAttribute("aria-hidden")'), "true");
    assert.ok((await run('document.querySelector("[data-patrol-history]").textContent')).includes("用验证码"));
    if (process.env.FOCUS_FRONTEND_QA_DIR) await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    if (process.env.FOCUS_FRONTEND_QA_DIR) fs.writeFileSync(path.join(process.env.FOCUS_FRONTEND_QA_DIR, "current-" + (await run("document.body.dataset.view")) + ".png"), (await win.webContents.capturePage()).toPNG());
    await run('document.querySelector("[data-action=focus-home]").click()');
    await until('document.body.dataset.view === "focus"');
    assert.ok((await run('document.querySelector("#app").textContent')).length > 100);
    assert.equal(await run('window.patrolFixture.historyListRequests'), 0);
    if (process.env.FOCUS_FRONTEND_QA_DIR) await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    if (process.env.FOCUS_FRONTEND_QA_DIR) fs.writeFileSync(path.join(process.env.FOCUS_FRONTEND_QA_DIR, "current-task.png"), (await win.webContents.capturePage()).toPNG());
    const snapshot = async name => {
      if (!process.env.FOCUS_FRONTEND_QA_DIR) return;
      await new Promise(resolve => setTimeout(resolve, 250));
      win.webContents.invalidate();
      await new Promise(resolve => setTimeout(resolve, 100));
      await run("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
      fs.writeFileSync(path.join(process.env.FOCUS_FRONTEND_QA_DIR, name + ".png"), (await win.webContents.capturePage()).toPNG());
    };
    const beforeAdmission = await run('state.details.get(state.activeTaskId).messages.length');
    await run('document.querySelector("#mainInput").value="任务 Loop 直接消息"; document.querySelector("#mainInput").dispatchEvent(new Event("input", {bubbles:true})); sendMain()');
    await until('document.querySelector(".task-admission-receipt")');
    assert.equal(await run('state.details.get(state.activeTaskId).messages.length'), beforeAdmission);
    assert.equal(await run('state.details.get(state.activeTaskId).active_run'), null);
    assert.equal(await run('document.querySelector("#mainInput").value'), "");
    await snapshot("task-admission");
    for (const [action, page] of [["show-plugins", "plugins"], ["show-memory", "memory"]]) {
      await run(`window.patrolFixture.pageError="隔离读取失败"; document.querySelector('[data-action=${action}]').click()`);
      await until(`document.body.dataset.view === '${page}' && document.querySelector('#app [role=alert]')`);
      assert.match(await run('document.querySelector("#app [role=alert]").textContent'), /隔离读取失败/);
      await run(`window.patrolFixture.pageError=null; document.querySelector('[data-action=refresh-${page}]').click()`);
      await until(`!document.querySelector('#app [role=alert]') && document.querySelector('[data-page-search=${page}]')`);
      await snapshot(page);
      assert.equal(await run('document.querySelector("[data-nav-key][aria-current=page]").dataset.navKey'), page);
      await run(`document.querySelector('[data-page-search=${page}]').value='无匹配记录'; document.querySelector('[data-page-search=${page}]').dispatchEvent(new Event('input', {bubbles:true}))`);
      assert.equal(await run('document.querySelectorAll("#app .plugin-card, #app .memory-card").length'), 0);
      await run(`document.querySelector('[data-page-search=${page}]').value=''; document.querySelector('[data-page-search=${page}]').dispatchEvent(new Event('input', {bubbles:true}))`);
    }
    await run('document.querySelector("[data-action=show-plugins]").click()');
    await until('document.body.dataset.view === "plugins" && !state.plugins.loading');
    await run('document.querySelector("[data-action=reload-plugins]").click()');
    await until('window.patrolFixture.reloads === 1 && !state.plugins.loading');
    await run('document.querySelector("[data-action=show-assembly]").click()');
    await until('document.querySelector(".task-workspace-layout.is-assembly") && state.details.get("assembly")?.harness_mode === "assembly"');
    assert.equal(await run('activeTask().harness_mode'), "assembly");
    await snapshot("standalone");
    await run('document.querySelector("[data-action=show-map]").click()');
    await until('document.body.dataset.view === "map"');
    const exactEdges = await run('(() => { const manifest={nodes:[{context_id:"A",title:"A"},{context_id:"B",title:"B"}],edges:["A1","A2"].map(source_revision_id=>({source_context_id:"A",source_revision_id,target_context_id:"B",target_revision_id:"B1"}))}; const host=document.createElement("div"); host.innerHTML=FocusPortfolioMapView.render(manifest); app.append(host); const counts=[]; for(let i=0;i<4;i++){ FocusPortfolioMapView.reconcile(host,manifest); counts.push(host.querySelectorAll("path[data-edge-id]").length); } const titles=[...host.querySelectorAll("path[data-edge-id] title")].map(node=>node.textContent).sort(); FocusPortfolioMapView.reconcile(host,{...manifest,edges:[manifest.edges[1]]}); const remaining=host.querySelector("path[data-edge-id] title").textContent; host.remove(); return {counts,titles,remaining}; })()');
    assert.deepEqual(exactEdges, {counts:[2,2,2,2],titles:["A1 → B1","A2 → B1"],remaining:"A2 → B1"});
    await run('mapPortfolio={workspaceId:state.patrolWorkspace.workspace_id,snapshot:{nodes:[{context_id:"root",revision_id:"r1",generation:1}],edges:[],complete:true},manifest:{loop_id:"loop-completion_check",nodes:[{context_id:"root",title:"首线程"}]}}; state.mapViewMode="graph"; state.selectionMode=false; state.soldierArmed=false; renderMap()');
    await run('document.querySelector("[data-action=toggle-selection-mode]").click(); document.querySelector(".portfolio-context-node").click()');
    assert.equal(await run('state.selectedContextIds.has("root")'), true);
    assert.equal(await run('document.activeElement.dataset.contextId'), "root");
    assert.equal(await run('document.querySelector(".portfolio-context-node").getAttribute("aria-pressed")'), "true");
    await win.webContents.sendInputEvent({type:"keyDown",keyCode:"Space"});
    await win.webContents.sendInputEvent({type:"keyUp",keyCode:"Space"});
    await until('!state.selectedContextIds.has("root")');
    assert.equal(await run('document.activeElement.dataset.contextId'), "root");
    await run('document.querySelector("[data-action=toggle-selection-mode]").click()');
    await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await run('document.querySelector("[data-action=arm-soldier]").click()');
    await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await run('document.querySelector(".portfolio-context-node").focus()');
    assert.equal(await run('document.activeElement.dataset.contextId'), "root");
    await win.webContents.sendInputEvent({type:"keyDown",keyCode:"Enter"});
    await win.webContents.sendInputEvent({type:"char",keyCode:"Enter"});
    await win.webContents.sendInputEvent({type:"keyUp",keyCode:"Enter"});
    await until('document.body.dataset.view === "draft" && state.activeTaskId === "root"');
    assert.deepEqual(await run('window.patrolFixture.draftOpens'), ["root"]);
    await run('state.soldierArmed=false; document.querySelector("[data-action=show-map]").click()');
    await until('document.body.dataset.view === "map"');
    await snapshot("map");
    await run('document.querySelector("[data-action=open-settings]").click()');
    await until('document.querySelector("#settingsDialog").open');
    await snapshot("settings");
    await run('document.querySelector("[data-action=close-settings]").click()');
    await until('!document.querySelector("#settingsDialog").open');
    await run('document.querySelector("[data-action=show-patrol]:not([data-patrol-switch])").click()');
    await until('document.querySelector("[data-patrol-composer]")');
    win.setContentSize(390, 844);
    await run('document.querySelector("[data-patrol-history-open]").click()');
    assert.equal(await run('document.querySelector("[data-patrol-dialog]").open'), true);
    await snapshot("narrow-history");
    await win.webContents.sendInputEvent({ type: "keyDown", keyCode: "Escape" });
    await until('!document.querySelector("[data-patrol-dialog]").open');
    assert.equal(await run('document.activeElement.hasAttribute("data-patrol-history-open")'), true);
    await snapshot("narrow-patrol");
    win.setContentSize(1280, 860);
    win.webContents.setZoomFactor(2);
    await snapshot("zoom-patrol");
    const overflow = await run('({document:document.documentElement.scrollWidth,viewport:innerWidth})');
    assert.ok(overflow.document <= overflow.viewport + 1, JSON.stringify(overflow));
    win.webContents.setZoomFactor(1);
    win.setContentSize(1280, 860);
    await run('state.tasks=[]; state.activeTaskId=null; state.patrolWorkspace=null; state.patrolWorkspaceBeforePick=null; localStorage.removeItem("focus-patrol-workspace"); window.patrolFixture.pagesEmpty=true; state.plugins.plugins=[]; state.memory.memories=[]; render()');
    for (const [action, page] of [["focus-home", "focus"], ["show-map", "map"], ["show-plugins", "plugins"], ["show-memory", "memory"], ["show-assembly", "focus"], ["show-patrol", "patrol"]]) {
      await run(`document.querySelector('[data-action=${action}]:not([data-patrol-switch])').click()`);
      await until(`document.body.dataset.view === '${page}'`);
      assert.equal(await run('document.querySelector("#app").textContent.includes("桌面服务未就绪")'), false);
    }
    assert.deepEqual(errors, []);
    console.log("PATROL_UI_PASS: four first types, rapid inputs, draft, folding, requests, independent progress/facts, ordinary page");
    win.destroy(); app.quit();
  }).catch(error => { console.error(error); app.exit(1); });
}
